import { Metadata } from "next";
import { Header, Footer } from "@/components/layout";

export const metadata: Metadata = {
  title: "Terms of Service | Rulebook",
  description: "Terms of Service for Rulebook - Rules and guidelines for using our app.",
};

export default function TermsPage() {
  return (
    <>
      <Header />
      <main className="min-h-screen bg-surface-secondary pt-24 md:pt-28">
        <div className="container-landing py-12 md:py-20">
          <div className="max-w-3xl mx-auto">
            <h1 className="font-black text-4xl uppercase mb-2">Terms of Service</h1>
            <p className="text-content-secondary mb-8">Last updated: December 2024</p>

            <div className="bg-white border-3 border-black shadow-brutalist-md p-8 space-y-8">
              <section>
                <h2 className="font-black text-xl uppercase mb-4">Acceptance of Terms</h2>
                <p className="text-content-secondary leading-relaxed">
                  By downloading, installing, or using Rulebook, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the app.
                </p>
              </section>

              <section>
                <h2 className="font-black text-xl uppercase mb-4">Description of Service</h2>
                <p className="text-content-secondary leading-relaxed">
                  Rulebook is a mobile application that uses AI to identify board games from photos and generate rule summaries. The service requires an internet connection for scanning features but allows offline access to previously saved rules.
                </p>
              </section>

              <section>
                <h2 className="font-black text-xl uppercase mb-4">Credits and Purchases</h2>
                <ul className="list-disc list-inside text-content-secondary space-y-2">
                  <li>New users receive 3 free scan credits upon completing onboarding</li>
                  <li>Additional credits can be purchased through in-app purchases</li>
                  <li>Credits never expire and are non-refundable</li>
                  <li>One credit is consumed per successful game scan</li>
                  <li>Credits are tied to your device and cannot be transferred</li>
                </ul>
              </section>

              <section>
                <h2 className="font-black text-xl uppercase mb-4">AI-Generated Content</h2>
                <p className="text-content-secondary leading-relaxed mb-4">
                  Game rules and summaries are generated by artificial intelligence. While we strive for accuracy, we cannot guarantee that all generated content is complete or error-free.
                </p>
                <p className="text-content-secondary leading-relaxed">
                  Users should verify critical rules with official game documentation when necessary. Rulebook is intended as a learning aid, not a replacement for official rulebooks.
                </p>
              </section>

              <section>
                <h2 className="font-black text-xl uppercase mb-4">Acceptable Use</h2>
                <p className="text-content-secondary leading-relaxed mb-4">You agree not to:</p>
                <ul className="list-disc list-inside text-content-secondary space-y-2">
                  <li>Use the app for any illegal purpose</li>
                  <li>Attempt to reverse engineer or modify the app</li>
                  <li>Upload inappropriate or copyrighted content</li>
                  <li>Interfere with or disrupt the service</li>
                  <li>Resell or redistribute generated content for commercial purposes</li>
                </ul>
              </section>

              <section>
                <h2 className="font-black text-xl uppercase mb-4">Intellectual Property</h2>
                <p className="text-content-secondary leading-relaxed">
                  The Rulebook app, including its design, code, and branding, is owned by us. Board game names, images, and rules are the property of their respective publishers. We do not claim ownership of any third-party intellectual property.
                </p>
              </section>

              <section>
                <h2 className="font-black text-xl uppercase mb-4">Limitation of Liability</h2>
                <p className="text-content-secondary leading-relaxed">
                  Rulebook is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from the use or inability to use the app, including but not limited to inaccurate rule generation or service interruptions.
                </p>
              </section>

              <section>
                <h2 className="font-black text-xl uppercase mb-4">Termination</h2>
                <p className="text-content-secondary leading-relaxed">
                  We reserve the right to terminate or suspend access to the app at any time, without prior notice, for conduct that we believe violates these Terms or is harmful to other users.
                </p>
              </section>

              <section>
                <h2 className="font-black text-xl uppercase mb-4">Changes to Terms</h2>
                <p className="text-content-secondary leading-relaxed">
                  We may modify these Terms at any time. Continued use of the app after changes constitutes acceptance of the new Terms.
                </p>
              </section>

              <section>
                <h2 className="font-black text-xl uppercase mb-4">Contact</h2>
                <p className="text-content-secondary leading-relaxed">
                  Questions about these Terms? Contact us at{" "}
                  <a href="mailto:legal@rulebook.app" className="text-brutalist-orange underline">
                    legal@rulebook.app
                  </a>
                </p>
              </section>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
